dist: bionic
language: ruby
sudo: false
group: stable vm_type=N1-highmem-4

cache:
  directories:
    - vendor/bundle
    - /tmp/cache/unicode_conformance
    - /tmp/beanstalkd-1.10
    - node_modules
    - $HOME/.nvm

services:
  - memcached
  - redis-server
  - mysql

addons:
  postgresql: 10
  chrome: stable
  apt:
    sources:
      - sourceline: "ppa:jonathonf/ffmpeg-3"
      - sourceline: "ppa:ubuntuhandbook1/apps"
    packages:
      - ffmpeg
      - mupdf
      - mupdf-tools
      - poppler-utils

bundler_args: --jobs $(nproc) --retry 3
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler"
  - "[[ -z $encrypted_0fb9444d0374_key && -z $encrypted_0fb9444d0374_iv ]] || openssl aes-256-cbc -K $encrypted_0fb9444d0374_key -iv $encrypted_0fb9444d0374_iv -in activestorage/test/service/configurations.yml.enc -out activestorage/test/service/configurations.yml -d"
  - "[[ $GEM != 'actioncable:integration' ]] || yarn install"
  - "[[ $GEM != 'actionview:ujs' ]] || nvm install node"
  - "[[ $GEM != 'actionview:ujs' ]] || node --version"
  - "[[ $GEM != 'actionview:ujs' ]] || (cd actionview && npm install)"
  - "[[ $GEM != 'railties' ]] || (curl -o- -L https://yarnpkg.com/install.sh | bash)"
  - "[[ $GEM != 'railties' ]] || export PATH=$HOME/.yarn/bin:$PATH"
  - "[[ $GEM != 'activerecord:postgresql' ]] || sudo mount -o remount,size=50% /var/ramfs"

before_script:
  # Set Sauce Labs username and access key. Obfuscated, purposefully not encrypted.
  # Decodes to e.g. `export VARIABLE=VALUE`
  - $(base64 --decode <<< "ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9YTAzNTM0M2YtZTkyMi00MGIzLWFhM2MtMDZiM2VhNjM1YzQ4")
  - $(base64 --decode <<< "ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPXJ1YnlvbnJhaWxz")
  - "[[ $GEM != 'railties' ]] || (cd actionview && yarn build)"
  - "[[ $GEM != 'railties' ]] || (cd railties/test/isolation/assets && yarn install)"

script: 'ci/travis.rb'

env:
  global:
    - "JRUBY_OPTS='--dev -J-Xmx1024M'"
    - "PARALLEL_WORKERS=$(nproc)"
  matrix:
    - "GEM=activerecord:sqlite3"
    - "GEM=activerecord:postgresql"
    - "GEM=activerecord:mysql2"

rvm:
  - 2.5.3

matrix:
  include:
    - rvm: 2.5.3
      env: "GEM=actionview:ujs"
    - rvm: 2.5.3
      env: "GEM=railties"
    - rvm: 2.5.3
      env:
        - "GEM=activerecord:mysql2 MYSQL=mariadb"
      before_install:
        - "sudo mysql_upgrade"
        - "sudo service mysql restart"
      addons:
        mariadb: 10.3


  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: "GEM=actioncable:integration"
  fast_finish: true

